### ISSUE TITLE
Warning on class comparision

### ISSUE THREAD

**Issue by surmann** [mnwright/ranger#19]
Hallo Marvin,
I get the following warning message with the CRAN version 0.2.7:
```
Warning message:
In if (class(data) == "gwaa.data") { :
  the condition has length > 1 and only the first element will be used
```
You can reproduce it by the following MWE:
```
library(data.table)
data("iris")
ranger(Species~., data = as.data.table(iris))
```

Thanks for your work!

**Comment by mnwright** [comment]
This is already fixed here on GitHub. See pull request #11. Coming to CRAN soon.

**Comment by MahdiSafarpour** [comment]
Hello Marvin,

This problem still remains in version ‘0.1.6.33’. Does this message mean that we cannot trust on outputs?
I get this message when I run following codes:
Ranger=ranger(Species~ . , data =iris, probability=TRUE, write.forest=TRUE, importance="pairwise")
prediction=predict(Ranger, data=iris ,type = "response")

Thank you in advance for your reply!
